//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColabManager360.Infrastructure.Repositories.Reports.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportQuery() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColabManager360.Infrastructure.Repositories.Reports.Resources.ReportQuery", typeof(ReportQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///p.Id as PeriodId,
        ///p.MaximumDays,
        ///p.MaximumHours, 
        ///c.LegalName,
        ///c.CommercialName,
        ///c3.Name as CountryName,
        ///wa.Name WorkAreaName,
        ///wat.Name WorkAreaTeamName,
        ///at.Description ActivityTypeName,
        ///cs.Description CompanyServiceName,
        ///CONCAT(pi2.LastName1, &apos; &apos;, pi2.LastName2) as FullLastName,
        ///CONCAT(pi2.FirstName1 , &apos; &apos;, pi2.FirstName2) as FullFirstName,
        ///a.Description, 
        ///a.DurationHours,
        ///a.TicketCode 
        ///FROM Activities a
        ///INNER JOIN Periods p ON p.Id =a.PeriodId
        ///--INNER JOIN ActivitiesDetail ad on a [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string DailyHoursInput {
            get {
                return ResourceManager.GetString("DailyHoursInput", resourceCulture);
            }
        }
    }
}
